server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #当前微服务（发现服务7001）不应注册在Eureka中
    fetchRegistry: false #不通过Eureka获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  security:
#    user:
#      name: wuzheng
#      password: hello
#      roles: USER
