server:
  port: 8001
logging:
  config: classpath:log/logback.xml
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wuzheng.microcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-8001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: carins_iip
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

